services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api

  api:
    build:
      context: .
      target: final
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: src/
        - action: rebuild
          path: Cargo.toml
        - action: rebuild
          path: Cargo.lock
        - action: rebuild
          path: migrations/

  db:
    image: postgres:18.1-trixie
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=rscord
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend-network:

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
