name: test-backend

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: rscord_test
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: rscord_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-backend -> target"

      - name: build
        run: cargo build --release
        working-directory: src-backend/
      - name: run tests
        run: cargo test --release
        working-directory: src-backend/
        env:
          TEST_DATABASE_URL: postgres://rscord_test:test_password@localhost:5432/rscord_test
      - name: run clippy
        run: cargo clippy -- -D clippy::correctness -D pedantic -D clippy::nursery -D clippy::suspicious -D clippy::perf -D clippy::allow_attributes -D clippy::cfg_not_test -D clippy::field_scoped_visibility_modifiers -W clippy::filetype_is_file -W clippy::complexity -W clippy::style -W clippy::cargo -W clippy::unwrap_used -W clippy::assertions_on_result_states -W clippy::clone_on_ref_ptr -W clippy::empty_drop -W clippy::empty_enum_variants_with_brackets -W clippy::empty_structs_with_brackets -W clippy::default_trait_access -W clippy::default_union_representation -W clippy::decimal_literal_representation -W clippy::shadow_same -D deprecated_safe -D let_underscore -D nonstandard_style -W rust_2024_compatibility -W future_incompatible -W keyword_idents
        working-directory: src-backend/
